### ISSUE TITLE
Update copyright info

### ISSUE THREAD

**Issue by jseitter** [blech-lang/blech#6]
bump copyright to 2022

**Comment by schorg** [comment]
Where ?
Usually all files contain a copyright notice on top of the file. It says
// Copyright (c) 2019 - for information on the respective copyright owner
2019 -   means starts in 2019 and is ongoing.
@jseitter do you think this is not correct ? 
Are there any files where the notice is different ?

**Comment by jseitter** [comment]
found it at least in blechc --version
`./blechc --version
Blech Compiler 0.5.3+0  Copyright (C) 2019-2020 see blech-lang.org
`

**Comment by schorg** [comment]
I found it will be release in a minute.

**Comment by schorg** [comment]
> Blech Compiler 0.7.2+0  Copyright (C) 2019-2022 see blech-lang.org

@jseitter you should update to the latest release it fixes several bugs.

**Comment by schorg** [comment]
@jseitter fixed. Thanks for the hint. Older version will not be updated.
